#spring:
#  datasource:
#    driverClassName: org.h2.Driver
#    url: jdbc:h2:mem:test;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
#  jpa:
#    hibernate:
#      ddl-auto: validate

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/stuha18
    username: stuha18
    password: stuha18
    driverClassName: org.postgresql.Driver
    initialize: false
  jpa:
    hibernate:
      ddl-auto: validate
#    show-sql: true
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
#logging:
#  path: /var/log/stuha18-server

push:
  public: BP1L6NuCPiYPiT9gCTJhxLxouPpFoSQZ3JurtuXkeEPAv7eeClEh3pBdFlUEtweIoKlw4S0fXmJAcrqefcTqhzo=
  private: AJ3sSQnTt7/THVKnjTn/RHrwJWQPgMiBXZl7NL7EcPWD
